<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\LetterTemplate;

class SuratTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            [
                'name' => 'Surat Keterangan Siswa Aktif',
                'paper_size' => 'A4',
                'use_system_kop' => true,
                'content' => '<p class="ql-align-center"><strong>SURAT KETERANGAN SISWA AKTIF</strong></p><p class="ql-align-center">Nomor: [NOMOR_SURAT]</p><p><br></p><p>Yang bertanda tangan di bawah ini, Kepala {{ nama_sekolah }}, menerangkan bahwa:</p><p><br></p><p>Nama&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <strong>{{ nama_siswa }}</strong></p><p>NISN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ nisn }}</p><p>Tempat, Tgl Lahir&nbsp;&nbsp;: {{ tempat_lahir }}, {{ tanggal_lahir }}</p><p>Kelas&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ kelas }}</p><p>Alamat&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ alamat_siswa }}</p><p><br></p><p>Adalah benar-benar siswa aktif di sekolah kami pada Tahun Pelajaran {{ tahun_pelajaran }}.</p><p><br></p><p>Demikian surat keterangan ini dibuat untuk dapat dipergunakan sebagaimana mestinya.</p><p><br></p><p><br></p><p class="ql-align-right">{{ tempat }}, {{ tanggal_surat }}</p><p class="ql-align-right">Kepala Sekolah,</p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><strong><u>{{ nama_kepala_sekolah }}</u></strong></p><p class="ql-align-right">NIP. {{ nip_kepala_sekolah }}</p>',
            ],
            [
                'name' => 'Surat Keterangan Lulus',
                'paper_size' => 'A4',
                'use_system_kop' => true,
                'content' => '<p class="ql-align-center"><strong>SURAT KETERANGAN LULUS</strong></p><p class="ql-align-center">Nomor: [NOMOR_SURAT]</p><p><br></p><p>Yang bertanda tangan di bawah ini, Kepala {{ nama_sekolah }}, menerangkan bahwa:</p><p><br></p><p>Nama&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <strong>{{ nama_siswa }}</strong></p><p>NISN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ nisn }}</p><p>Tempat, Tgl Lahir&nbsp;&nbsp;: {{ tempat_lahir }}, {{ tanggal_lahir }}</p><p>Nama Orang Tua&nbsp;&nbsp;&nbsp;: {{ nama_orang_tua }}</p><p>Alamat&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ alamat_siswa }}</p><p><br></p><p>Telah menyelesaikan seluruh program pembelajaran dan dinyatakan <strong>LULUS</strong> dari {{ nama_sekolah }} pada Tahun Pelajaran {{ tahun_pelajaran }}.</p><p><br></p><p>Demikian surat keterangan ini dibuat untuk dapat dipergunakan sebagaimana mestinya.</p><p><br></p><p><br></p><p class="ql-align-right">{{ tempat }}, {{ tanggal_surat }}</p><p class="ql-align-right">Kepala Sekolah,</p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><strong><u>{{ nama_kepala_sekolah }}</u></strong></p><p class="ql-align-right">NIP. {{ nip_kepala_sekolah }}</p>',
            ],
            [
                'name' => 'Surat Keterangan Pindah',
                'paper_size' => 'A4',
                'use_system_kop' => true,
                'content' => '<p class="ql-align-center"><strong>SURAT KETERANGAN PINDAH</strong></p><p class="ql-align-center">Nomor: [NOMOR_SURAT]</p><p><br></p><p>Yang bertanda tangan di bawah ini, Kepala {{ nama_sekolah }}, menerangkan bahwa:</p><p><br></p><p>Nama&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <strong>{{ nama_siswa }}</strong></p><p>NISN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ nisn }}</p><p>Tempat, Tgl Lahir&nbsp;&nbsp;: {{ tempat_lahir }}, {{ tanggal_lahir }}</p><p>Kelas Terakhir&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ kelas }}</p><p>Nama Orang Tua&nbsp;&nbsp;&nbsp;: {{ nama_orang_tua }}</p><p>Alamat&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ alamat_siswa }}</p><p><br></p><p>Siswa tersebut telah keluar/pindah dari sekolah kami sejak tanggal {{ tanggal_pindah }} dengan alasan {{ alasan_pindah }}.</p><p><br></p><p>Sekolah Tujuan: <strong>{{ sekolah_tujuan }}</strong></p><p><br></p><p>Demikian surat keterangan ini dibuat untuk dapat dipergunakan sebagaimana mestinya.</p><p><br></p><p><br></p><p class="ql-align-right">{{ tempat }}, {{ tanggal_surat }}</p><p class="ql-align-right">Kepala Sekolah,</p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><strong><u>{{ nama_kepala_sekolah }}</u></strong></p><p class="ql-align-right">NIP. {{ nip_kepala_sekolah }}</p>',
            ],
            [
                'name' => 'Surat Keterangan Berkelakuan Baik',
                'paper_size' => 'A4',
                'use_system_kop' => true,
                'content' => '<p class="ql-align-center"><strong>SURAT KETERANGAN BERKELAKUAN BAIK</strong></p><p class="ql-align-center">Nomor: [NOMOR_SURAT]</p><p><br></p><p>Yang bertanda tangan di bawah ini, Kepala {{ nama_sekolah }}, menerangkan bahwa:</p><p><br></p><p>Nama&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <strong>{{ nama_siswa }}</strong></p><p>NISN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ nisn }}</p><p>Tempat, Tgl Lahir&nbsp;&nbsp;: {{ tempat_lahir }}, {{ tanggal_lahir }}</p><p>Kelas&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ kelas }}</p><p>Alamat&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ alamat_siswa }}</p><p><br></p><p class="ql-align-justify">Adalah benar-benar siswa di sekolah kami yang selama menempuh pendidikan <strong>BERKELAKUAN BAIK</strong>, tidak pernah terlibat dalam tindakan kriminal, dan tidak pernah terlibat dalam penyalahgunaan narkotika dan obat-obatan terlarang.</p><p><br></p><p>Demikian surat keterangan ini dibuat dengan sebenar-benarnya untuk dapat dipergunakan sebagaimana mestinya.</p><p><br></p><p><br></p><p class="ql-align-right">{{ tempat }}, {{ tanggal_surat }}</p><p class="ql-align-right">Kepala Sekolah,</p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><strong><u>{{ nama_kepala_sekolah }}</u></strong></p><p class="ql-align-right">NIP. {{ nip_kepala_sekolah }}</p>',
            ],
            [
                'name' => 'Surat Keterangan Tidak Mampu',
                'paper_size' => 'A4',
                'use_system_kop' => true,
                'content' => '<p class="ql-align-center"><strong><u>SURAT KETERANGAN</u></strong></p><p class="ql-align-center">Nomor: [NOMOR_SURAT]</p><p><br></p><p>Yang bertanda tangan di bawah ini, Kepala Sekolah, menerangkan bahwa:</p><p><br></p><p>Nama Lengkap : {{ nama_siswa }}</p><p>NIS/NISN : {{ nis }} / {{ nisn }}</p><p>Kelas : {{ kelas }}</p><p>Nama Orang Tua : {{ nama_ayah }}</p><p>Pekerjaan Orang Tua : {{ pekerjaan_ayah }}</p><p><br></p><p>Adalah benar siswa dari keluarga tidak mampu dan layak mendapatkan bantuan pendidikan.</p><p><br></p><p>Demikian surat keterangan ini dibuat untuk dapat dipergunakan sebagaimana mestinya.</p><p><br></p><p><br></p><p class="ql-align-right">{{ tempat }}, {{ tanggal_surat }}</p><p class="ql-align-right">Kepala Sekolah,</p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><u><strong>{{ nama_kepala_sekolah }}</strong></u></p><p class="ql-align-right">NIP. {{ nip_kepala_sekolah }}</p>',
            ],
            [
                'name' => 'Surat Rekomendasi',
                'paper_size' => 'A4',
                'use_system_kop' => true,
                'content' => '<p class="ql-align-center"><strong>SURAT REKOMENDASI</strong></p><p class="ql-align-center">Nomor: [NOMOR_SURAT]</p><p><br></p><p>Yang bertanda tangan di bawah ini:</p><p><br></p><p>Nama&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ nama_kepala_sekolah }}</p><p>NIP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ nip_kepala_sekolah }}</p><p>Jabatan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: Kepala {{ nama_sekolah }}</p><p><br></p><p>Dengan ini memberikan rekomendasi kepada:</p><p><br></p><p>Nama&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <strong>{{ nama_siswa }}</strong></p><p>NISN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ nisn }}</p><p>Tempat, Tgl Lahir&nbsp;&nbsp;: {{ tempat_lahir }}, {{ tanggal_lahir }}</p><p>Kelas&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ kelas }}</p><p><br></p><p class="ql-align-justify">Untuk {{ keperluan_rekomendasi }}. Siswa tersebut selama menempuh pendidikan di sekolah kami menunjukkan prestasi yang baik, berkelakuan baik, dan aktif dalam kegiatan sekolah.</p><p><br></p><p>Demikian surat rekomendasi ini dibuat dengan sebenar-benarnya untuk dapat dipergunakan sebagaimana mestinya.</p><p><br></p><p><br></p><p class="ql-align-right">{{ tempat }}, {{ tanggal_surat }}</p><p class="ql-align-right">Kepala Sekolah,</p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><strong><u>{{ nama_kepala_sekolah }}</u></strong></p><p class="ql-align-right">NIP. {{ nip_kepala_sekolah }}</p>',
            ],
            [
                'name' => 'Surat Panggilan Orang Tua',
                'paper_size' => 'A4',
                'use_system_kop' => true,
                'content' => '<p>Nomor : [NOMOR_SURAT]</p><p>Lamp. : -</p><p>Hal : <strong>Panggilan Orang Tua/Wali</strong></p><p><br></p><p>Kepada Yth.</p><p>Bapak/Ibu Orang Tua/Wali dari:</p><p><br></p><p>Nama : {{ nama_siswa }}</p><p>Kelas : {{ kelas }}</p><p><br></p><p>di Tempat</p><p><br></p><p>Dengan hormat,</p><p><br></p><p>Bersama ini kami mengharapkan kehadiran Bapak/Ibu pada:</p><p><br></p><p>Hari/Tanggal : {{ hari_tanggal }}</p><p>Pukul : {{ waktu }} WIB</p><p>Tempat : Ruang Kepala Sekolah</p><p>Keperluan : {{ keperluan }}</p><p><br></p><p>Atas perhatian dan kehadiran Bapak/Ibu, kami ucapkan terima kasih.</p><p><br></p><p><br></p><p class="ql-align-right">{{ tempat }}, {{ tanggal_surat }}</p><p class="ql-align-right">Kepala Sekolah,</p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><u><strong>{{ nama_kepala_sekolah }}</strong></u></p><p class="ql-align-right">NIP. {{ nip_kepala_sekolah }}</p>',
            ],
            [
                'name' => 'Surat Undangan Rapat Wali Murid',
                'paper_size' => 'A4',
                'use_system_kop' => true,
                'content' => '<p>Nomor : [NOMOR_SURAT]</p><p>Lamp. : -</p><p>Hal : <strong>Undangan Rapat Wali Murid</strong></p><p><br></p><p>Kepada Yth.</p><p>Bapak/Ibu Wali Murid</p><p>di Tempat</p><p><br></p><p>Dengan hormat,</p><p><br></p><p>Dalam rangka {{ agenda_rapat }}, kami mengundang Bapak/Ibu untuk hadir pada:</p><p><br></p><p>Hari/Tanggal : {{ hari_tanggal }}</p><p>Pukul : {{ waktu }} WIB</p><p>Tempat : {{ tempat_rapat }}</p><p>Acara : {{ acara }}</p><p><br></p><p>Mengingat pentingnya acara ini, kami mohon Bapak/Ibu dapat hadir tepat waktu.</p><p><br></p><p>Atas perhatian dan kehadiran Bapak/Ibu, kami ucapkan terima kasih.</p><p><br></p><p><br></p><p class="ql-align-right">{{ tempat }}, {{ tanggal_surat }}</p><p class="ql-align-right">Kepala Sekolah,</p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><u><strong>{{ nama_kepala_sekolah }}</strong></u></p><p class="ql-align-right">NIP. {{ nip_kepala_sekolah }}</p>',
            ],
            [
                'name' => 'Surat Tugas',
                'paper_size' => 'A4',
                'use_system_kop' => true,
                'content' => '<p class="ql-align-center"><strong>SURAT TUGAS</strong></p><p class="ql-align-center">Nomor: [NOMOR_SURAT]</p><p><br></p><p>Yang bertanda tangan di bawah ini, Kepala {{ nama_sekolah }}, memberikan tugas kepada:</p><p><br></p><p>Nama&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <strong>{{ nama_guru }}</strong></p><p>NIP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ nip_guru }}</p><p>Pangkat/Gol&nbsp;&nbsp;&nbsp;&nbsp;: {{ pangkat_golongan }}</p><p>Jabatan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ jabatan_guru }}</p><p><br></p><p>Untuk melaksanakan tugas:</p><p><br></p><p>Kegiatan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ nama_kegiatan }}</p><p>Hari/Tanggal&nbsp;&nbsp;&nbsp;&nbsp;: {{ hari_tanggal }}</p><p>Tempat&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ tempat_kegiatan }}</p><p><br></p><p>Demikian surat tugas ini dibuat untuk dilaksanakan dengan penuh tanggung jawab.</p><p><br></p><p><br></p><p class="ql-align-right">{{ tempat }}, {{ tanggal_surat }}</p><p class="ql-align-right">Kepala Sekolah,</p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><strong><u>{{ nama_kepala_sekolah }}</u></strong></p><p class="ql-align-right">NIP. {{ nip_kepala_sekolah }}</p>',
            ],
            [
                'name' => 'Surat Izin Kegiatan',
                'paper_size' => 'A4',
                'use_system_kop' => true,
                'content' => '<p class="ql-align-center"><strong>SURAT IZIN KEGIATAN</strong></p><p class="ql-align-center">Nomor: [NOMOR_SURAT]</p><p><br></p><p>Yang bertanda tangan di bawah ini:</p><p><br></p><p>Nama&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ nama_kepala_sekolah }}</p><p>NIP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ nip_kepala_sekolah }}</p><p>Jabatan&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: Kepala Sekolah</p><p><br></p><p>Dengan ini memberikan izin kepada:</p><p><br></p><p>Nama Kegiatan&nbsp;&nbsp;&nbsp;: <strong>{{ nama_kegiatan }}</strong></p><p>Penyelenggara&nbsp;&nbsp;&nbsp;: {{ penyelenggara }}</p><p>Hari/Tanggal&nbsp;&nbsp;&nbsp;&nbsp;: {{ hari_tanggal }}</p><p>Waktu&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ waktu_kegiatan }}</p><p>Tempat&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ tempat_kegiatan }}</p><p>Peserta&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ peserta }}</p><p><br></p><p>Demikian surat izin ini dibuat untuk dapat dilaksanakan dengan penuh tanggung jawab.</p><p><br></p><p><br></p><p class="ql-align-right">{{ tempat }}, {{ tanggal_surat }}</p><p class="ql-align-right">Kepala Sekolah,</p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><strong><u>{{ nama_kepala_sekolah }}</u></strong></p><p class="ql-align-right">NIP. {{ nip_kepala_sekolah }}</p>',
            ],
            [
                'name' => 'Surat Undangan Rapat Orang Tua',
                'paper_size' => 'A4',
                'use_system_kop' => true,
                'content' => '<p class="ql-align-center"><strong>SURAT UNDANGAN</strong></p><p class="ql-align-center">Nomor: [NOMOR_SURAT]</p><p><br></p><p>Kepada Yth.</p><p>Bapak/Ibu Orang Tua/Wali Siswa</p><p>Kelas {{ kelas }}</p><p>di Tempat</p><p><br></p><p>Dengan hormat,</p><p><br></p><p class="ql-align-justify">Sehubungan dengan {{ perihal_rapat }}, maka kami mengundang Bapak/Ibu untuk hadir pada:</p><p><br></p><p>Hari/Tanggal&nbsp;&nbsp;&nbsp;&nbsp;: {{ hari_tanggal }}</p><p>Waktu&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ waktu_rapat }}</p><p>Tempat&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ tempat_rapat }}</p><p>Acara&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ acara_rapat }}</p><p><br></p><p class="ql-align-justify">Mengingat pentingnya acara ini, kami mohon Bapak/Ibu dapat hadir tepat waktu. Atas perhatian dan kehadiran Bapak/Ibu, kami ucapkan terima kasih.</p><p><br></p><p><br></p><p class="ql-align-right">{{ tempat }}, {{ tanggal_surat }}</p><p class="ql-align-right">Kepala Sekolah,</p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><strong><u>{{ nama_kepala_sekolah }}</u></strong></p><p class="ql-align-right">NIP. {{ nip_kepala_sekolah }}</p>',
            ],
            [
                'name' => 'Surat Pemberitahuan',
                'paper_size' => 'A4',
                'use_system_kop' => true,
                'content' => '<p class="ql-align-center"><strong>SURAT PEMBERITAHUAN</strong></p><p class="ql-align-center">Nomor: [NOMOR_SURAT]</p><p><br></p><p>Kepada Yth.</p><p>{{ tujuan_surat }}</p><p>di Tempat</p><p><br></p><p>Dengan hormat,</p><p><br></p><p class="ql-align-justify">{{ isi_pemberitahuan }}</p><p><br></p><p class="ql-align-justify">Demikian pemberitahuan ini kami sampaikan. Atas perhatian dan kerjasamanya, kami ucapkan terima kasih.</p><p><br></p><p><br></p><p class="ql-align-right">{{ tempat }}, {{ tanggal_surat }}</p><p class="ql-align-right">Kepala Sekolah,</p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><strong><u>{{ nama_kepala_sekolah }}</u></strong></p><p class="ql-align-right">NIP. {{ nip_kepala_sekolah }}</p>',
            ],
            [
                'name' => 'Surat Peringatan Siswa',
                'paper_size' => 'A4',
                'use_system_kop' => true,
                'content' => '<p class="ql-align-center"><strong>SURAT PERINGATAN {{ tingkat_peringatan }}</strong></p><p class="ql-align-center">Nomor: [NOMOR_SURAT]</p><p><br></p><p>Kepada Yth.</p><p>Orang Tua/Wali dari:</p><p><br></p><p>Nama&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <strong>{{ nama_siswa }}</strong></p><p>NISN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ nisn }}</p><p>Kelas&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: {{ kelas }}</p><p><br></p><p>di Tempat</p><p><br></p><p>Dengan hormat,</p><p><br></p><p class="ql-align-justify">Berdasarkan laporan dan hasil evaluasi, kami sampaikan bahwa siswa tersebut di atas telah melakukan pelanggaran:</p><p><br></p><p class="ql-align-justify"><strong>{{ jenis_pelanggaran }}</strong></p><p><br></p><p class="ql-align-justify">Melalui surat ini kami memberikan Peringatan {{ tingkat_peringatan }} dan memohon kepada Bapak/Ibu untuk memberikan perhatian dan bimbingan lebih kepada putra/putrinya agar tidak mengulangi pelanggaran yang sama.</p><p><br></p><p>Demikian surat peringatan ini disampaikan. Atas perhatiannya, kami ucapkan terima kasih.</p><p><br></p><p><br></p><p class="ql-align-right">{{ tempat }}, {{ tanggal_surat }}</p><p class="ql-align-right">Kepala Sekolah,</p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><br></p><p class="ql-align-right"><strong><u>{{ nama_kepala_sekolah }}</u></strong></p><p class="ql-align-right">NIP. {{ nip_kepala_sekolah }}</p>',
            ],
        ];

        foreach ($templates as $template) {
            LetterTemplate::updateOrCreate(
                ['name' => $template['name']],
                $template
            );
        }
    }
}
